title: Geeks for Social Change
description: >
  Working with community organisations and activist groups towards a fairer society using technology, communication, and education.
paginate:	2 # The number of posts to show per page on your homepage
name: "Dr Kim Foale"
markdown: kramdown
destination: docs
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
  - jekyll-compose
paginate_path: "/blog/page:num/"
paginate: 5
